name: alamodeapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0  
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  country_pickers: ^2.0.0
  pin_code_fields: ^8.0.1
  responsive_grid_list: ^1.4.0
  carousel_slider_plus: ^7.0.0
  flutter_svg_provider: ^1.0.7
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.2
  http: ^1.1.2

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
